#!/bin/sh -e

date=$(date +%Y%m%d)a
date2=$(date +%d/%m/%Y)
date3=$(date '+%a, %d %h %Y')
index=$(printf %d '"a')

while [ -f "$date" ]; do
    index=$((index + 1))
    date=${date%%?}$(printf %b "$(printf \\x%x "$index")")
done

cat > "$date.txt" <<EOF
---
title: "$date2: $1"
---
EOF

rss="<item>
<title>$date2: $1</title>
<description></description>
<link>https://k1ss.org/blog/$date/</link>
<guid isPermaLink=\"true\">https://k1ss.org/blog/$date/</guid>
<pubDate>$date3 00:00:00 +0000</pubDate>
</item>"

entry="- <a href=/blog/$date.html>$date2: $1</a>"

while read -r line; do
    printf '%s\n' "$line"

    case $line in *'<atom'*) printf '%s\n' "$rss"; esac
done < blog.xml > blog.xml.new

mv -f blog.xml.new blog.xml

while read -r line; do
    printf '%s\n' "$line"

    case $line in -*) printf '%s\n' "$entry"; esac
done < ../blog.txt > ../blog.txt.new

mv -f ../blog.txt.new ../blog.txt
